version: "3.0"
services:
  database:
    container_name: database_test
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database-data:/var/lib/postgres/data

volumes:
  database-data:
